name: "Terraform Plan and Deploy"

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature**'
    paths-ignore:
      - '**/README.md'
      - '**/.github/workflows/**.yaml'


permissions:
  id-token: write # This is required for aws oidc connection
  contents: write # This is required for actions/checkout
  issues: write
  pull-requests: write # This is required for gh bot to comment PR

jobs:
  cicd:
    uses: subhamay-bhattacharyya/9999-reusable-wf/.github/workflows/tf-cicd-create.yaml@main
    with:
      deploy-reviewer-test: 142895397   # This is the user id of the reviewer - Subhamay
      deploy-reviewer-prod: 150314255   # This is the user id of the reviewer - Thomas
      pr-approver: 144537759            # This is the user id of the reviewer - Samsung
    secrets:
      git-token: ${{ secrets.GIT_TOKEN }}